### PR TITLE
Adding couch_index_plugin:before_open/2 EPI hook

### PR DESCRIPTION
**Pull request by iilyak**

### CODE REVIEW

**Comment by eiri** [comment]
+1

**Comment by rnewson** [comment]
please provide an explanation. A sentence is not sufficient.

**Comment by iilyak** [comment]
@rnewson: Short description is added to commit message.

**Comment by rnewson** [comment]
ok thanks. In future please include it in the description of the pull request too.

+1

**Comment by iilyak** [comment]
@rnewson Could you merge it I don't have power.

**Comment by eiri** [comment]
All right, this PR has two +1s (one's mine, admittedly), I tested it locally and it doesn't break anything and I tested it with a custom plugin and it works as expected. I'm going to rebase and merge it.

**Comment by kxepal** [comment]
@eiri please! thanks (: and +1 here.

**Comment by iilyak** [comment]
Already implemented

**Pull request closed without merging**
